datasources:
  principal:
    #jdbcUrl: jdbc:postgresql://ec2-3-91-127-228.compute-1.amazonaws.com:5432/dc0b5re52fr7c?ssl=true&amp;sslfactory=org.postgresql.ssl.NonValidatingFactory
    jdbcUrl: jdbc:postgresql://ec2-3-91-127-228.compute-1.amazonaws.com:5432/dc0b5re52fr7c?ssl=true&amp;sslfactory=org.postgresql.ssl.NonValidatingFactory&sslmode=require
    username: skiwkdnirccpsz
    password: 21beab87befa216463edb748375a97b56f8d85138691fc0ca92eb78209c19431
    maximumPoolSize: 1
  test:
    jdbcUrl: jdbc:h2:file:./target/db/testdb;MODE=PostgreSQL
    username: sa
    password:
    maximumPoolSize: 1

# Spring properties
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://localhost/test
  application:
    name: user-service  # Service registers under this name

endpoints:
  health:
    enabled: yes
  shutdown:
    enabled: yes

management:
  context-path: /admin
logging:
  level:
    org:
      springframework:
        web:
          client: DEBUG

# HTTP Server
server:
  port: 8080   # HTTP (Tomcat) port